# Generated by Django 3.0.5 on 2020-04-16 18:29

from django.db import migrations, models
import onlineShop.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200302_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_desc',
            field=models.FileField(blank=True, null=True, upload_to='desc_files', validators=[onlineShop.main.models.validate_extension]),
        ),
    ]
