# Generated by Django 3.0.5 on 2020-04-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_category_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFullInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_info', models.TextField(default='')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
    ]
