# Generated by Django 2.0 on 2020-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'moderator'), (3, 'editor')], default=1),
        ),
    ]
