# Generated by Django 3.0.5 on 2020-04-16 17:32

from django.db import migrations, models
import onlineShop.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos', validators=[onlineShop.api.models.validate_file_size, onlineShop.api.models.validate_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
